spring:
  datasource:
    url: jdbc:mysql://172.188.32.189:3306/demo?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 172.188.32.189
    port: 6379
